global:
  scrape_interval: 5s # How often to scrape targets
  evaluation_interval: 5s

scrape_configs:
  - job_name: "order_service"
    static_configs:
      - targets: ["order_service:8001"]

  - job_name: "payment_service"
    static_configs:
      - targets: ["payment_service:8002"]

  - job_name: "shipping_service"
    static_configs:
      - targets: ["shipping_service:8003"]
